wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1669000002.959955
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 23
      4: 3.9.12
      5: 0.13.5
      8:
      - 5
    viz:
      confusion_matrix:
        historyFieldSettings:
          key: confusion_matrix
          x-axis: _step
        id: wandb/confusion_matrix/v1
